### ISSUE TITLE
Schematic and BOM?

### ISSUE THREAD

**Issue by jamesy0ung** [Element18592/360-NAND-X#1]
Hey @Element18592 can we have the schematic and BOM so we can make this ourselves?

**Comment by Element18592** [comment]
Haven't had the time to put together a BOM as it hasn't been a priority for me with my current projects and other things I have going on. As soon as I can dedicate some time to sit down and grab the values of each component I'll put one up.

**Comment by jamesy0ung** [comment]
Awesome. Can the chip (can't find an image anywhere) be programmed with standard development tools (not ck3i)?

**Comment by Element18592** [comment]
Yes it's an LPC2148. It can be programmed with a generic USB to TLL serial adapter and an application like Flash Magic. I threw together a quick diagram to show the pinout.

![Update NANDX](https://user-images.githubusercontent.com/40620345/120022122-8ec00e80-bfb1-11eb-8d26-5b014382c84d.png)

**Comment by gregtwallace** [comment]
This is great, thanks.  BOM would be fantastic so we can get these made up.

**Comment by Element18592** [comment]
> Good morning, it really lacks the BOM to be perfect, I'm starting to learn the maintenance of xbox360 games and now I need to buy a pcb like this. Is it the same one they sell in the market? If yes I will see these values. And when I'm done, I'll put it here. Hugs to everyone. Is there an open board from X360USBPRO2?

Yes it's the same as the one on the market. I have one here I've been wanting to pull the values from myself since release but my work hasn't given me the time to set aside to create the BOM yet.

**Comment by jamesy0ung** [comment]
@gregtwallace 
No, I'll just be using a Raspberry Pi Pico going forward. I've already modded all my 360s with a MTX programmer (painful, but I won't need to do it again)

**Comment by rsenas** [comment]
Thanks.
